blank_issues_enabled: true
contact_links:
  - name: "ğŸ’¬ ì§ˆë¬¸ì´ë‚˜ í† ë¡ "
    url: https://github.com/gimgawon/fastapi-notes/discussions
    about: "í•™ìŠµ ë‚´ìš©ì— ëŒ€í•œ ì§ˆë¬¸ì´ë‚˜ í† ë¡ ì€ Discussionsë¥¼ ì´ìš©í•´ì£¼ì„¸ìš”."
